# Copyright 2016 ParanoidAndroid Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file was automatically generated by vendor/lge/bullhead/extract.sh

# An overlay for features that depend on proprietary files
DEVICE_PACKAGE_OVERLAYS := vendor/lge/bullhead/overlay

BOARD_PREBUILT_VENDORIMAGE := proprietary/vendor.img

PRODUCT_COPY_FILES += \
    vendor/lge/bullhead/proprietary/system/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/lge/bullhead/proprietary/system/bin/btnvtool:system/bin/btnvtool \
    vendor/lge/bullhead/proprietary/system/bin/cnd:system/bin/cnd \
    vendor/lge/bullhead/proprietary/system/bin/cnss-daemon:system/bin/cnss-daemon \
    vendor/lge/bullhead/proprietary/system/bin/fingerprintd:system/bin/fingerprintd \
    vendor/lge/bullhead/proprietary/system/bin/imsdatadaemon:system/bin/imsdatadaemon \
    vendor/lge/bullhead/proprietary/system/bin/imsqmidaemon:system/bin/imsqmidaemon \
    vendor/lge/bullhead/proprietary/system/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
    vendor/lge/bullhead/proprietary/system/bin/irsc_util:system/bin/irsc_util \
    vendor/lge/bullhead/proprietary/system/bin/location-mq:system/bin/location-mq \
    vendor/lge/bullhead/proprietary/system/bin/loc_launcher:system/bin/loc_launcher \
    vendor/lge/bullhead/proprietary/system/bin/lowi-server:system/bin/lowi-server \
    vendor/lge/bullhead/proprietary/system/bin/msm_irqbalance:system/bin/msm_irqbalance \
    vendor/lge/bullhead/proprietary/system/bin/netmgrd:system/bin/netmgrd \
    vendor/lge/bullhead/proprietary/system/bin/nl_listener:system/bin/nl_listener \
    vendor/lge/bullhead/proprietary/system/bin/perfd:system/bin/perfd \
    vendor/lge/bullhead/proprietary/system/bin/pm-proxy:system/bin/pm-proxy \
    vendor/lge/bullhead/proprietary/system/bin/pm-service:system/bin/pm-service \
    vendor/lge/bullhead/proprietary/system/bin/port-bridge:system/bin/port-bridge \
    vendor/lge/bullhead/proprietary/system/bin/qmakernote-xtract:system/bin/qmakernote-xtract \
    vendor/lge/bullhead/proprietary/system/bin/qmuxd:system/bin/qmuxd \
    vendor/lge/bullhead/proprietary/system/bin/radish:system/bin/radish \
    vendor/lge/bullhead/proprietary/system/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lge/bullhead/proprietary/system/bin/subsystem_ramdump:system/bin/subsystem_ramdump \
    vendor/lge/bullhead/proprietary/system/bin/thermal-engine:system/bin/thermal-engine \
    vendor/lge/bullhead/proprietary/system/bin/time_daemon:system/bin/time_daemon \
    vendor/lge/bullhead/proprietary/system/bin/wcnss_filter:system/bin/wcnss_filter \
    vendor/lge/bullhead/proprietary/system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/lge/bullhead/proprietary/system/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/lge/bullhead/proprietary/system/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/lge/bullhead/proprietary/system/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/lge/bullhead/proprietary/system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/lge/bullhead/proprietary/system/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/lge/bullhead/proprietary/system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/lge/bullhead/proprietary/system/etc/cne/profile.txt:system/etc/cne/profile.txt \
    vendor/lge/bullhead/proprietary/system/etc/data/dsi_config.xml:system/etc/data/dsi_config.xml \
    vendor/lge/bullhead/proprietary/system/etc/data/netmgr_config.xml:system/etc/data/netmgr_config.xml \
    vendor/lge/bullhead/proprietary/system/etc/data/qmi_config.xml:system/etc/data/qmi_config.xml \
    vendor/lge/bullhead/proprietary/system/etc/flp.conf:system/etc/flp.conf \
    vendor/lge/bullhead/proprietary/system/etc/izat.conf:system/etc/izat.conf \
    vendor/lge/bullhead/proprietary/system/etc/lowi.conf:system/etc/lowi.conf \
    vendor/lge/bullhead/proprietary/system/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/lge/bullhead/proprietary/system/etc/permissions/com.android.omadm.service.xml:system/etc/permissions/com.android.omadm.service.xml \
    vendor/lge/bullhead/proprietary/system/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/lge/bullhead/proprietary/system/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/lge/bullhead/proprietary/system/etc/permissions/rcsservice.xml:system/etc/permissions/rcsservice.xml \
    vendor/lge/bullhead/proprietary/system/etc/qcril.db:system/etc/qcril.db \
    vendor/lge/bullhead/proprietary/system/etc/sap.conf:system/etc/sap.conf \
    vendor/lge/bullhead/proprietary/system/etc/sysconfig/whitelist_com.android.omadm.service.xml:system/etc/sysconfig/whitelist_com.android.omadm.service.xml \
    vendor/lge/bullhead/proprietary/system/etc/thermal-engine-8992.conf:system/etc/thermal-engine-8992.conf \
    vendor/lge/bullhead/proprietary/system/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/lge/bullhead/proprietary/system/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/lge/bullhead/proprietary/system/framework/rcsimssettings.jar:system/framework/rcsimssettings.jar \
    vendor/lge/bullhead/proprietary/system/framework/rcsservice.jar:system/framework/rcsservice.jar \
    vendor/lge/bullhead/proprietary/system/lib64/hw/activity_recognition.bullhead.so:system/lib64/hw/activity_recognition.bullhead.so \
    vendor/lge/bullhead/proprietary/system/lib64/hw/fingerprint.bullhead.so:system/lib64/hw/fingerprint.bullhead.so \
    vendor/lge/bullhead/proprietary/system/lib64/hw/gps.msm8992.so:system/lib64/hw/gps.msm8992.so \
    vendor/lge/bullhead/proprietary/system/lib64/hw/nfc_nci.bullhead.so:system/lib64/hw/nfc_nci.bullhead.so \
    vendor/lge/bullhead/proprietary/system/lib64/lib_fpc_tac_shared.so:system/lib64/lib_fpc_tac_shared.so \
    vendor/lge/bullhead/proprietary/system/lib64/libgps.utils.so:system/lib64/libgps.utils.so \
    vendor/lge/bullhead/proprietary/system/lib64/libloc_api_v02.so:system/lib64/libloc_api_v02.so \
    vendor/lge/bullhead/proprietary/system/lib64/libloc_core.so:system/lib64/libloc_core.so \
    vendor/lge/bullhead/proprietary/system/lib64/libloc_ds_api.so:system/lib64/libloc_ds_api.so \
    vendor/lge/bullhead/proprietary/system/lib64/libloc_eng.so:system/lib64/libloc_eng.so \
    vendor/lge/bullhead/proprietary/system/lib/hw/activity_recognition.bullhead.so:system/lib/hw/activity_recognition.bullhead.so \
    vendor/lge/bullhead/proprietary/system/lib/hw/fingerprint.bullhead.so:system/lib/hw/fingerprint.bullhead.so \
    vendor/lge/bullhead/proprietary/system/lib/hw/gps.msm8992.so:system/lib/hw/gps.msm8992.so \
    vendor/lge/bullhead/proprietary/system/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
    vendor/lge/bullhead/proprietary/system/lib/hw/nfc_nci.bullhead.so:system/lib/hw/nfc_nci.bullhead.so \
    vendor/lge/bullhead/proprietary/system/lib/libdmengine.so:system/lib/libdmengine.so \
    vendor/lge/bullhead/proprietary/system/lib/libdmjavaplugin.so:system/lib/libdmjavaplugin.so \
    vendor/lge/bullhead/proprietary/system/lib/lib_fpc_tac_shared.so:system/lib/lib_fpc_tac_shared.so \
    vendor/lge/bullhead/proprietary/system/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/lge/bullhead/proprietary/system/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/lge/bullhead/proprietary/system/lib/libloc_core.so:system/lib/libloc_core.so \
    vendor/lge/bullhead/proprietary/system/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/lge/bullhead/proprietary/system/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/lge/bullhead/proprietary/system/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/lge/bullhead/proprietary/system/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/lge/bullhead/proprietary/system/lib/soundfx/libfmas.so:system/lib/soundfx/libfmas.so \
    vendor/lge/bullhead/proprietary/system/priv-app/DMService/lib/arm/libdmengine.so:system/priv-app/DMService/lib/arm/libdmengine.so \
    vendor/lge/bullhead/proprietary/system/priv-app/DMService/lib/arm/libdmjavaplugin.so:system/priv-app/DMService/lib/arm/libdmjavaplugin.so

PRODUCT_PACKAGES += \
    HiddenMenu \
    RCSBootstraputil \
    RcsImsBootstraputil \
    TimeService \
    atfwd \
    CNEService \
    ConnMO \
    DCMO \
    DiagMon \
    DMConfigUpdate \
    DMService \
    Entitlement \
    HotwordEnrollment \
    LifeTimerService \
    qcrilmsgtunnel \
    SprintDM
